# CMake generated Testfile for 
# Source directory: /home/marksa/dev/git/fork/gnucash/libgnucash/engine/test
# Build directory: /home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/libgnucash/engine/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-link "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-link")
add_test(test-load-engine "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-load-engine")
set_tests_properties(test-load-engine PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-guid "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-guid")
set_tests_properties(test-guid PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-object "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-object")
set_tests_properties(test-object PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-commodities "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-commodities")
set_tests_properties(test-commodities PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-qof "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-qof")
set_tests_properties(test-qof PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-engine "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-engine")
set_tests_properties(test-engine PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-account-object "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-account-object")
set_tests_properties(test-account-object PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-group-vs-book "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-group-vs-book")
set_tests_properties(test-group-vs-book PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-lots "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-lots")
set_tests_properties(test-lots PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-querynew "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-querynew")
set_tests_properties(test-querynew PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-query "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-query")
set_tests_properties(test-query PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-split-vs-account "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-split-vs-account")
set_tests_properties(test-split-vs-account PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-transaction-reversal "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-transaction-reversal")
set_tests_properties(test-transaction-reversal PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-transaction-voiding "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-transaction-voiding")
set_tests_properties(test-transaction-voiding PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-recurrence "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-recurrence")
set_tests_properties(test-recurrence PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-business "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-business")
set_tests_properties(test-business PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-address "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-address")
set_tests_properties(test-address PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-customer "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-customer")
set_tests_properties(test-customer PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-employee "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-employee")
set_tests_properties(test-employee PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-job "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-job")
set_tests_properties(test-job PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-vendor "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-vendor")
set_tests_properties(test-vendor PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-numeric "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-numeric")
set_tests_properties(test-numeric PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-gnc-guid "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-gnc-guid")
set_tests_properties(test-gnc-guid PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-kvp-value "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-kvp-value")
set_tests_properties(test-kvp-value PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-qofsession "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-qofsession")
set_tests_properties(test-qofsession PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-gnc-int128 "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-gnc-int128")
set_tests_properties(test-gnc-int128 PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-gnc-rational "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-gnc-rational")
set_tests_properties(test-gnc-rational PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-gnc-numeric "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-gnc-numeric")
set_tests_properties(test-gnc-numeric PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-gnc-timezone "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-gnc-timezone")
set_tests_properties(test-gnc-timezone PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-gnc-datetime "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-gnc-datetime")
set_tests_properties(test-gnc-datetime PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-import-map "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-import-map")
set_tests_properties(test-import-map PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-qofquerycore "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-qofquerycore")
set_tests_properties(test-qofquerycore PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4")
add_test(test-scm-query "/usr/bin/cmake" "-E" "env" "GNC_UNINSTALLED=YES" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4" "GNC_UNINSTALLED=yes" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4" "LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash" "GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash" "GUILE=/usr/bin/guile" "GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash/scm/ccache/2.0" "GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-baz" "/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/bin/test-scm-query")
set_tests_properties(test-scm-query PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4;GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-baz;")
add_test(test-account "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/test-account.scm" "-c" "(exit (run-test))")
set_tests_properties(test-account PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-baz;")
add_test(test-create-account "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/test-create-account.scm" "-c" "(exit (run-test))")
set_tests_properties(test-create-account PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-baz;")
add_test(test-split "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/test-split.scm" "-c" "(exit (run-test))")
set_tests_properties(test-split PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib:/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build-gnucash-3.4/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/engine/test/mod-baz;")
