# CMake generated Testfile for 
# Source directory: /home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test
# Build directory: /home/marksa/dev/git/fork/gnucash/build_2019-03-13/libgnucash/gnc-module/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-load-c "/usr/bin/cmake" "-E" "env" "GNC_UNINSTALLED=YES" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "GNC_UNINSTALLED=yes" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash" "GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash" "GUILE=/usr/bin/guile" "GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0" "GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz" "GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test" "/home/marksa/dev/git/fork/gnucash/build_2019-03-13/bin/test-load-c")
set_tests_properties(test-load-c PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
add_test(test-modsysver "/usr/bin/cmake" "-E" "env" "GNC_UNINSTALLED=YES" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "GNC_UNINSTALLED=yes" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash" "GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash" "GUILE=/usr/bin/guile" "GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0" "GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz" "/home/marksa/dev/git/fork/gnucash/build_2019-03-13/bin/test-modsysver")
set_tests_properties(test-modsysver PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;")
add_test(test-incompatdep "/usr/bin/cmake" "-E" "env" "GNC_UNINSTALLED=YES" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "GNC_UNINSTALLED=yes" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash" "GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash" "GUILE=/usr/bin/guile" "GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0" "GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz" "/home/marksa/dev/git/fork/gnucash/build_2019-03-13/bin/test-incompatdep")
set_tests_properties(test-incompatdep PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;")
add_test(test-agedver "/usr/bin/cmake" "-E" "env" "GNC_UNINSTALLED=YES" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "GNC_UNINSTALLED=yes" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash" "GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash" "GUILE=/usr/bin/guile" "GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0" "GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz" "GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test" "/home/marksa/dev/git/fork/gnucash/build_2019-03-13/bin/test-agedver")
set_tests_properties(test-agedver PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
add_test(test-dynload "/usr/bin/cmake" "-E" "env" "GNC_UNINSTALLED=YES" "GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13" "LIBDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib" "/home/marksa/dev/git/fork/gnucash/build_2019-03-13/bin/test-dynload")
set_tests_properties(test-dynload PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=YES;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LIBDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib")
add_test(test-gnc-module-scm-init "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/test-gnc-module-scm-init.scm" "-c" "(exit (run-test))")
set_tests_properties(test-gnc-module-scm-init PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
add_test(test-gnc-module-load-scm "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/test-gnc-module-load-scm.scm" "-c" "(exit (run-test))")
set_tests_properties(test-gnc-module-load-scm PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
add_test(test-gnc-module-swigged-c "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/test-gnc-module-swigged-c.scm" "-c" "(exit (run-test))")
set_tests_properties(test-gnc-module-swigged-c PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
add_test(test-gnc-module-load-deps "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/test-gnc-module-load-deps.scm" "-c" "(exit (run-test))")
set_tests_properties(test-gnc-module-load-deps PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
add_test(test-gnc-module-scm-dynload "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/test-gnc-module-scm-dynload.scm" "-c" "(exit (run-test))")
set_tests_properties(test-gnc-module-scm-dynload PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
add_test(test-gnc-module-scm-module "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/test-gnc-module-scm-module.scm" "-c" "(exit (run-test))")
set_tests_properties(test-gnc-module-scm-module PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
add_test(test-gnc-module-scm-multi "/usr/bin/cmake" "-E" "env" "/usr/bin/guile" "--debug" "-l" "/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/test-gnc-module-scm-multi.scm" "-c" "(exit (run-test))")
set_tests_properties(test-gnc-module-scm-multi PROPERTIES  ENVIRONMENT "GNC_UNINSTALLED=yes;GNC_BUILDDIR=/home/marksa/dev/git/fork/gnucash/build_2019-03-13;LD_LIBRARY_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash;GUILE=/usr/bin/guile;GUILE_LOAD_COMPILED_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/scm/ccache/2.0;GUILE_LOAD_PATH=/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-foo:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-bar:/home/marksa/dev/git/fork/gnucash/libgnucash/gnc-module/test/mod-baz;GNC_MODULE_PATH=/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash:/home/marksa/dev/git/fork/gnucash/build_2019-03-13/lib/gnucash/test")
subdirs("mod-foo")
subdirs("mod-bar")
subdirs("mod-baz")
subdirs("misc-mods")
